### ISSUE TITLE
Brackets expression is not working in MPS 2023.2

### ISSUE THREAD

**Issue by alexanderpann** [JetBrains/MPS-extensions#819]

**Comment by veldhvzbd** [comment]
And when you have an editor containing a BracketsCell, it generates code that does not compile:
The template template_BracketsCell_DeleteBracket contains a line `inner.smodelAttribute.addAll(node.smodelAttribute);` which get to be generated as `ListSequence.fromList(SLinkOperations.getChildren(inner, LINKS.smodelAttribute$KJ43)).addSequence(SLinkOperations.getChildren(node, LINKS.smodelAttribute$KJ43));`
The  Java compiler complains that `incompatible types: java.util.List<org.jetbrains.mps.openapi.model.SNode> cannot be converted to jetbrains.mps.internal.collections.runtime.ISequence<? extends org.jetbrains.mps.openapi.model.SNode>`.

**Comment by alexanderpann** [comment]
I don't know what happened but I can't reproduce my original issue and also not the issue with the generation.
